---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
  - repo: local
    hooks:
      - id: eslint
        name: lint source code
        entry: yarn lint --fix
        language: node
        files: '.*\.(js|vue)$'
